// Generated by CoffeeScript 1.8.0
var properties;

properties = [
  {
    address: '3030 16th Street',
    zipcode: '94103',
    blocklot: '3554010',
    location: {
      lat: 37.765208,
      lng: -122.4203596
    },
    owners: {
      'Jolish Limited Partnership': 100
    },
    notes: 'Station 40'
  }, {
    address: '3012 16th Street',
    zipcode: '94103',
    blocklot: '3554008',
    location: {
      lat: 37.765208,
      lng: -122.4201036
    },
    owners: {
      'Oded Schwartz & Ruth Rosenthal': 50,
      'Jolish Limited Partnership': 50
    }
  }, {
    address: '83 Weise Street',
    zipcode: '94103',
    blocklot: '3554053',
    location: {
      lat: 37.7654826,
      lng: -122.4204921
    },
    owners: {
      'Oded Schwartz & Ruth Rosenthal': 50,
      'Jolish Limited Partnership': 50
    }
  }, {
    address: '1381 9th Avenue',
    zipcode: '94122',
    blocklot: '1764017',
    location: {
      lat: 37.762512,
      lng: -122.46649
    },
    owners: {
      'Zepporah Glass Trust': 25,
      'Isaac Michael Safier': 25,
      'Jolish Limited Partnership': 50
    },
    notes: 'Former (?) headquarters of Craigslist, Inc.'
  }, {
    address: '672 Panorama Drive',
    zipcode: '94131',
    blocklot: '2787009',
    location: {
      lat: 37.7539019,
      lng: -122.452241
    },
    owners: {
      'Jolish Limited Partnership': 100
    }
  }, {
    address: '661 Panorama Drive',
    zipcode: '94131',
    blocklot: '2791004',
    location: {
      lat: 37.753541,
      lng: -122.451925
    },
    owners: {
      'Jolish Limited Partnership': 100
    }
  }, {
    address: '1096 South Van Ness Ave',
    zipcode: '94131',
    blocklot: '3615010',
    location: {
      lat: 37.755706,
      lng: -122.416879
    },
    owners: {
      'Oded Schwartz & Ruth Rosenthal': 30,
      'Barak & Taly Jolish': 70
    }
  }, {
    address: '2073 Mission Street',
    zipcode: '94110',
    blocklot: '3570048',
    location: {
      lat: 37.763779,
      lng: -122.4191205
    },
    owners: {
      'Oded Schwartz & Ruth Rosenthal': 33.33,
      'Barak & Taly Jolish': 33.33,
      'Rony Rolnizky & Lulu Carpenter': 33.33
    }
  }, {
    address: '2341 Union Street',
    zipcode: '94123',
    blocklot: '0538020',
    location: {
      lat: 37.796508,
      lng: -122.437804
    },
    owners: {
      'Oded Schwartz & Ruth Rosenthal': 100
    }
  }, {
    address: '26 Skyview Way',
    zipcode: '94131',
    blocklot: '2823B019',
    location: {
      lat: 37.749702,
      lng: -122.450101
    },
    owners: {
      'Oded Schwartz & Ruth Rosenthal': 100
    }
  }, {
    address: '798 Monterey Boulevard 1A',
    zipcode: '94131',
    blocklot: '3095055',
    location: {
      lat: 37.731799,
      lng: -122.453198
    },
    owners: {
      'Rony Rolnizky & Lulu Carpenter': 100
    }
  }, {
    address: '333 Grant Ave #303',
    zipcode: '94108',
    blocklot: '0286029',
    location: {
      lat: 37.790303,
      lng: -122.405833
    },
    owners: {
      'Isaac Michael Safier': 100
    }
  }, {
    address: '1601 Polk Street',
    zipcode: '94131',
    blocklot: '0622004',
    location: {
      lat: 37.7916202,
      lng: -122.4211143
    },
    owners: {
      'Barak & Taly Jolish': 100
    }
  }, {
    address: '3036 24th Street',
    zipcode: '94131',
    blocklot: '3640070',
    location: {
      lat: 37.7528038,
      lng: -122.4127172
    },
    owners: {
      'Barak & Taly Jolish': 100
    }
  }, {
    address: '425 1st Street #1902',
    zipcode: '94105',
    blocklot: '3765126',
    location: {
      lat: 37.7860587,
      lng: -122.3926328
    },
    owners: {
      'Glass Properties LP': 64,
      'Zepporah Glass Trust': 36
    }
  }, {
    address: '83 McAllister Street #506',
    zipcode: '94102',
    blocklot: '0351106',
    location: {
      lat: 37.78083,
      lng: -122.41333
    },
    owners: {
      'Isaac Michael Safier': 100
    }
  }, {
    address: '319 Panorama Drive',
    zipcode: '94131',
    blocklot: '2834014',
    location: {
      lat: 37.749767,
      lng: -122.45241
    },
    owners: {
      'Emanuel & Ahuva Jolish': 100
    }
  }, {
    address: '55 Skyview Way',
    zipcode: '94131',
    blocklot: '2823C006',
    location: {
      lat: 37.750561,
      lng: -122.45241
    },
    owners: {
      'Emanuel & Ahuva Jolish': 100
    }
  }, {
    address: '121 Devonshire Way',
    zipcode: '94131',
    blocklot: '2676021',
    location: {
      lat: 37.7554657,
      lng: -122.4603008
    },
    owners: {
      'Rony Rolnizky & Lulu Carpenter': 100
    }
  }, {
    address: '2432 Castro Street',
    zipcode: '94131',
    blocklot: '7537016',
    location: {
      lat: 37.741945,
      lng: -122.43348
    },
    owners: {
      'Barak & Taly Jolish': 100
    }
  }, {
    address: '2917 24th Street',
    zipcode: '94131',
    blocklot: '7537016',
    location: {
      lat: 37.75265,
      lng: -122.4105593
    },
    owners: {
      '2917-2919 24th Street Partners LLC': 100
    }
  }
];
